// npm run dev  => localhost:3000


import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

// this should really redirect to profile/[dynamic] if there's a username in the cookie jar
// or at least make a possible redirect predominant on this page

// TODO:
// challenge/[id].jsx
// just a DataGrid of the challenge

// TODO:
// challenge/current.jsx
// show best times per vehicle for current challenge's stage+class


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>DR2.0 Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {/* highest average scorers */}
        <table>
          <thead> {/* change this to a component that takes in number of props as header titles */}
            <tr>
              <th>Name</th>
              <th>Nationality</th>
              <th>Score</th>
            </tr>
          </thead>
          <tbody>

          </tbody>
        </table>





      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}